In [16]:
from control import *

control = Control("COM4")
control.repeat = 0

def get_feedback():
    global control
    org = control.ser.readline().decode().strip()
    print(org)

In [ ]:
control.start()

In [16]:
control.stop()

In [ ]:
get_feedback()

### 命令发送测试

In [17]:
control.init()

b'\xaa\xbb\x00\x00\x00'


1

In [18]:
control.open_plate()

b'\xaa\xbb\x03\x03\x00'


1

In [19]:
control.close_plate()

b'\xaa\xbb\x04\x04\x00'


1

In [20]:
control.ser.flushInput()
control.get_rfid()
get_feedback()
get_feedback()

b'\xaa\xbb\x02\x02\x00'
ACK
rfid:0


In [21]:
control.ser.flushInput()
#测试分药矩阵
pillList = np.zeros([4, 7], dtype=np.byte)
for r in range(4):
    for c in range(7):
        if(c % 2):
            pillList[r][c] = 1
print(pillList)          
control.send_data(pillList)
print("开始分药")
get_feedback()
get_feedback()
get_feedback()


b'\xaa\xbb\x05\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01!\x00'
开始分药
ACK
machine_state:FINISH
pill_remain:4


In [36]:
control.pause()

b'\xaa\xbb\x01\x01\x00'


1

### 参数设置测试

In [12]:
#初始值参考
control.set_turnMotor_speed(0.5)
control.set_conveyorMotor_speed(1)
control.set_upperOptocoupler_thresh(0.87)
control.set_lowerOptocoupler_thresh(0.92)
control.set_upperOptocoupler_noresp(50)
control.set_lowerOptocoupler_noresp(10)
control.set_turnMotor_delay_stop(0)
control.set_clean_speed(0.8)
control.set_clean_delay(6 * 1000)


b'\xaa\xbb\x08\x00\x00\x00\x00?G\x00'
b'\xaa\xbb\x08\x01\x00\x00\x80?\xc8\x00'
b'\xaa\xbb\x06\x00R\xb8^?\xad\x01'
b'\xaa\xbb\x06\x01\x1f\x85k?U\x01'
b'\xaa\xbb\x07\x002\x00\x00\x009\x00'
b'\xaa\xbb\x07\x01\n\x00\x00\x00\x12\x00'
b'\xaa\xbb\t\x00\x00\x00\x00\x00\t\x00'


1

In [21]:
#非阻塞发药
pillList = np.zeros([4, 7], dtype=np.byte)
for r in range(4):
    for c in range(7):
        if(r == 1 or r == 0):
            pillList[r][c] = 1
print(pillList)
control.send_data(pillList)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
b'\xaa\xbb\x05\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x13\x00'


False

In [20]:
control.set_turnMotor_speed(0.8)#0.8

b'\xaa\xbb\x08\x00\xcd\xccL?,\x02'


1

In [25]:
control.set_conveyorMotor_speed(1)

b'\xaa\xbb\x08\x01\x00\x00\x80?\xc8\x00'


1

In [ ]:
control.set_upperOptocoupler_thresh(0.5)#0.88

b'\xaa\xbb\x06\x00\x9a\x99\x99>\x10\x02'


1

In [10]:
control.set_lowerOptocoupler_thresh(0.96)#0.96

b'\xaa\xbb\x06\x01\xc3\xf5h?f\x02'
b'\xaa\xbb\x06\x01\xc3\xf5h?f\x02'


1

In [ ]:
control.set_upperOptocoupler_noresp(18)

b'\xaa\xbb\x07\x00<\x00\x00\x00C\x00'
b'\xaa\xbb\x07\x00<\x00\x00\x00C\x00'


1

In [ ]:
control.set_lowerOptocoupler_noresp(3)

b'\xaa\xbb\x07\x01\x14\x00\x00\x00\x1c\x00'
b'\xaa\xbb\x07\x01\x14\x00\x00\x00\x1c\x00'


1

In [5]:
control.set_turnMotor_delay_stop(0)

b'\xaa\xbb\t\x00\x00\x00\x00\x00\t\x00'


1

In [3]:
control.set_clean_speed(1)
control.set_clean_delay(10 * 1000)

b'\xaa\xbb\x0b\x00\x00\x80?\xca\x00'
b"\xaa\xbb\x0c\x10'\x00\x00C\x00"


1