In [39]:
from control import *

control = Dispenser("COM17")
control.repeat = 0

def get_feedback():
    global control
    org = control.ser.readline().decode().strip()
    print(org)

In [ ]:
control.start_dispenser_feedback_handler()

In [ ]:
control.stop_dispenser_feedback_handler()

In [ ]:
get_feedback()

### 命令发送测试

In [40]:
control.init()

[发送] b'\xaa\xbb\x00\x00\x00'


1

In [ ]:
control.open_plate()

In [ ]:
control.close_plate()

In [ ]:
control.ser.flushInput()
# control.get_rfid()
get_feedback()
get_feedback()

In [ ]:
control.ser.flushInput()
control.close_plate()
control.set_turnMotor_speed(0.5)#0.8
control.set_conveyorMotor_speed(0.4)
#测试分药矩阵
pillList = np.zeros([4, 7], dtype=np.byte)
for r in range(3):
    for c in range(7):
        if r == 0:
            pillList[r][c] = 1
print(pillList)          
control.send_data(pillList)
print("开始分药")
get_feedback()
get_feedback()
get_feedback()


[发送] b'\xaa\xbb\x04\x04\x00'
[发送] b'\xaa\xbb\x08\x00\x00\x00\x00?G\x00'
[发送] b'\xaa\xbb\x08\x01\xcd\xcc\xcc=\xab\x02'
[[1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[发送] b'\xaa\xbb\x05\x01\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c\x00'
开始分药
ACK
DONE
ACK


In [42]:
control.pause()

[发送] b'\xaa\xbb\x01\x01\x00'


1

### 参数设置测试

In [ ]:
#初始值参考
control.set_turnMotor_speed(0.5)
control.set_conveyorMotor_speed(1)
control.set_upperOptocoupler_thresh(0.87)
control.set_lowerOptocoupler_thresh(0.92)
control.set_upperOptocoupler_noresp(50)
control.set_lowerOptocoupler_noresp(10)
control.set_turnMotor_delay_stop(0)
control.set_clean_speed(1.5)
control.set_clean_delay(2.5 * 1000)


In [ ]:
#非阻塞发药
pillList = np.zeros([4, 7], dtype=np.byte)
for r in range(4):
    for c in range(7):
        if(r == 1 or r == 0):
            pillList[r][c] = 1
print(pillList)
control.send_data(pillList)

In [ ]:
control.set_turnMotor_speed(0.5)#0.8


实际上为舵机角度设置

In [ ]:
control.set_conveyorMotor_speed(0.1)

In [ ]:
control.set_upperOptocoupler_thresh(0.5)#0.88

In [ ]:
control.set_lowerOptocoupler_thresh(0.96)#0.96

In [ ]:
control.set_upperOptocoupler_noresp(18)

In [ ]:
control.set_lowerOptocoupler_noresp(3)

In [ ]:
control.set_turnMotor_delay_stop(0)

In [ ]:
# control.set_clean_speed(1)
control.set_clean_delay(3 * 1000)

In [ ]:
control.set_clean_speed(0.1)