创建分药机实例，通过串口连接分药机下位机


In [ ]:
from dispenser_controller import *
my_dispenser = DispenserController("COM14")  # 根据实际串口修改

[成功] 串口 COM14 连接成功
[启动] 串口信息接收线程已启动，现在可以看到所有串口消息


串口接收 >>> ACK
[通信确认] 收到ACK
串口接收 >>> DONE
[操作完成] 收到DONE
串口接收 >>> ACK
[通信确认] 收到ACK
串口接收 >>> DONE
[操作完成] 收到DONE
串口接收 >>> ACK
[通信确认] 收到ACK
串口接收 >>> DONE
[操作完成] 收到DONE
串口接收 >>> ACK
[通信确认] 收到ACK
串口接收 >>> DONE
[操作完成] 收到DONE
串口接收 >>> ACK
[通信确认] 收到ACK
串口接收 >>> pills in:1
串口接收 >>> pills in:2
串口接收 >>> pills out:1
[药片剩余] 剩余未发药片数量: 3
[发送ACK给分药机] aabb0a0a00
串口接收 >>> pills in:3
串口接收 >>> pills out:2
[药片剩余] 剩余未发药片数量: 2
[发送ACK给分药机] aabb0a0a00
串口接收 >>> pills out:3
[药片剩余] 剩余未发药片数量: 1
[发送ACK给分药机] aabb0a0a00
串口接收 >>> pills in:4
串口接收 >>> pills out:4
[药片剩余] 剩余未发药片数量: 0
[发送ACK给分药机] aabb0a0a00
串口接收 >>> machine_state:FINISH
[状态更新] 分药完成
串口接收 >>> pill_remain:3
串口接收 >>> ACK
[通信确认] 收到ACK
串口接收 >>> DONE
[操作完成] 收到DONE


重置分药机状态

In [3]:
my_dispenser.reset_dispenser()

[发送] aabb000000
[成功] 收到确认
[操作] 分药机已重置


0

打开舱门

In [4]:
my_dispenser.open_tray()

[发送] aabb030300
[成功] 收到确认


0

放入药盘后关闭舱门

In [5]:
my_dispenser.close_tray()

[发送] aabb040400
[成功] 收到确认


0

根据药片类型设置转盘速度和舵机角度，发送测试分药矩阵

In [6]:
# 创建测试分药矩阵
my_dispenser.set_turnMotor_speed(0.6)
my_dispenser.set_servo_angle(0.5)
pill_matrix = np.zeros([4, 7], dtype=np.byte)
for r in range(3):
    if r == 0:
        for c in range(7):
            if c % 2 == 0:
                pill_matrix[r][c] = 1
print(f"分药矩阵:\n{pill_matrix}")
# 发送分药命令
return_msg = my_dispenser.send_pill_matrix(pill_matrix)
print(f"[结果] 发送分药命令结果: {return_msg}")

[发送] aabb08009a99193f9301
[重发 1/5] 未收到确认，重新发送
[重发] aabb08009a99193f9301
[重发 2/5] 未收到确认，重新发送
[重发] aabb08009a99193f9301
[重发 3/5] 未收到确认，重新发送
[重发] aabb08009a99193f9301
[重发 4/5] 未收到确认，重新发送
[重发] aabb08009a99193f9301
[重发 5/5] 未收到确认，重新发送
[重发] aabb08009a99193f9301
[失败] 经过 5 次重发仍未收到确认
[发送] aabb08010000003f4800
[重发 1/5] 未收到确认，重新发送
[重发] aabb08010000003f4800
[重发 2/5] 未收到确认，重新发送
[重发] aabb08010000003f4800
[重发 3/5] 未收到确认，重新发送
[重发] aabb08010000003f4800
[重发 4/5] 未收到确认，重新发送
[重发] aabb08010000003f4800
[重发 5/5] 未收到确认，重新发送
[重发] aabb08010000003f4800
[失败] 经过 5 次重发仍未收到确认
分药矩阵:
[[1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[发送] aabb05010001000100010000000000000000000000000000000000000000000900
[成功] 收到确认
[结果] 发送分药命令结果: True


In [7]:
my_dispenser.pause_dispenser()

[发送] aabb010100
[成功] 收到确认


0

In [8]:
my_dispenser.stop_dispenser_feedback_handler()

[成功] 串口信息接收线程已正常结束
