创建分药机实例，通过串口连接分药机下位机


In [1]:
from dispenser_controller import *
my_dispenser = DispenserController()


In [ ]:
my_dispenser.initialize_dispenser()

[Initialize] Starting dispenser initialization...
[Search] Searching for dispenser device...
[Info] Found 3 serial port devices:
  - COM19: USB-SERIAL CH340 (COM19)
    Manufacturer: wch.cn
    VID:PID: 1A86:7523
  - COM3: 蓝牙链接上的标准串行 (COM3)
    Manufacturer: Microsoft
  - COM4: 蓝牙链接上的标准串行 (COM4)
    Manufacturer: Microsoft
    [Match] CH340 chip detected: +50
    [Match] USB-SERIAL detected: +30
    [Match] Manufacturer detected: +40
    [Match] VID:PID detected(1A86:7523): +60
    [Match] USB device detected: +10
[Match] Found potential dispenser device: COM19 (match score: 190)
[Select] Auto-selected device: COM19
  Description: USB-SERIAL CH340 (COM19)
  Manufacturer: wch.cn
[Success] Serial port COM19 connected successfully
[Start] Serial message receiver thread started, now you can see all serial messages
[Send] aabb000000
Serial received >>> ACK
[Communication Confirmation] ACK received
[Success] Confirmation received
Serial received >>> DONE
[Operation Complete] DONE received
[O

True

Serial received >>> ACK
[Communication Confirmation] ACK received
Serial received >>> DONE
[Operation Complete] DONE received
Serial received >>> ACK
[Communication Confirmation] ACK received
Serial received >>> ACK
[Communication Confirmation] ACK received
Serial received >>> ACK
[Communication Confirmation] ACK received
Serial received >>> pills in:1
Serial received >>> pills out:1
[Pills Remaining] Remaining undispensed pills: 13
[Send ACK to dispenser] aabb0a0a00
Serial received >>> pills in:2
Serial received >>> pills in:3
Serial received >>> pills out:2
[Pills Remaining] Remaining undispensed pills: 12
[Send ACK to dispenser] aabb0a0a00
Serial received >>> pills out:3
[Pills Remaining] Remaining undispensed pills: 11
[Send ACK to dispenser] aabb0a0a00
Serial received >>> pills in:4
Serial received >>> pills out:4
[Pills Remaining] Remaining undispensed pills: 10
[Send ACK to dispenser] aabb0a0a00
Serial received >>> pills in:5
Serial received >>> pills out:5
[Pills Remaining] Rem

重置分药机状态

In [ ]:
my_dispenser.reset_dispenser()

打开舱门

In [5]:
my_dispenser.open_tray()

[Send] aabb030300
[Success] Confirmation received


0

放入药盘后关闭舱门

In [ ]:
my_dispenser.close_tray()

In [ ]:
my_dispenser.set_turnMotor_speed(0.6)

In [ ]:
my_dispenser.set_servo_angle(1.0)

根据药片类型设置转盘速度和舵机角度，发送测试分药矩阵

In [4]:
# 创建测试分药矩阵
my_dispenser.set_turnMotor_speed(0.15)
my_dispenser.set_servo_angle(1.0)
pill_matrix = np.zeros([4, 7], dtype=np.byte)
for r in range(3):
    if r < 2:
        for c in range(7):
            # if c % 2 == 0:
            pill_matrix[r][c] = 1
print(f"分药矩阵:\n{pill_matrix}")
# 发送分药命令
return_msg = my_dispenser.send_pill_matrix(pill_matrix)
print(f"[结果] 发送分药命令结果: {return_msg}")

[Send] aabb08009a99193e9201
[Success] Confirmation received
[Send] aabb08010000803fc800
[Success] Confirmation received
分药矩阵:
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[Send] aabb05010101010101010101010101010100000000000000000000000000001300
[Success] Confirmation received
[结果] 发送分药命令结果: True


In [ ]:
my_dispenser.pause_dispenser()

In [ ]:
my_dispenser.stop_dispenser_feedback_handler()